services:
  selenium-hub:
    image: selenium/hub:4.9.0-20230421
    container_name: selenium-hub
    ports:
      - "4444:4444"
    platform: linux/amd64

  chrome-node:
    image: selenium/node-chrome:4.9.0-20230421
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm
    platform: linux/amd64

  test-container:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium-hub
    environment:
      - SELENIUM_HUB=http://selenium-hub:4444
    platform: linux/amd64

networks:
  default:
    name: selenium-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16